// This file is auto-generated by the build process.
namespace Telerik.SvgIcons
{
    public static class SvgIcon
    {
        public static ISvgIcon CaretTr => new CaretTr();
        public static ISvgIcon CaretBr => new CaretBr();
        public static ISvgIcon CaretBl => new CaretBl();
        public static ISvgIcon CaretTl => new CaretTl();
        public static ISvgIcon CaretAltUp => new CaretAltUp();
        public static ISvgIcon CaretAltRight => new CaretAltRight();
        public static ISvgIcon CaretAltDown => new CaretAltDown();
        public static ISvgIcon CaretAltLeft => new CaretAltLeft();
        public static ISvgIcon CaretAltToTop => new CaretAltToTop();
        public static ISvgIcon CaretAltToRight => new CaretAltToRight();
        public static ISvgIcon CaretAltToBottom => new CaretAltToBottom();
        public static ISvgIcon CaretAltToLeft => new CaretAltToLeft();
        public static ISvgIcon CaretDoubleAltUp => new CaretDoubleAltUp();
        public static ISvgIcon CaretDoubleAltRight => new CaretDoubleAltRight();
        public static ISvgIcon CaretDoubleAltDown => new CaretDoubleAltDown();
        public static ISvgIcon CaretDoubleAltLeft => new CaretDoubleAltLeft();
        public static ISvgIcon CaretAltExpand => new CaretAltExpand();
        public static ISvgIcon ArrowsNoChange => new ArrowsNoChange();
        public static ISvgIcon ArrowOverflowDown => new ArrowOverflowDown();
        public static ISvgIcon ChevronUp => new ChevronUp();
        public static ISvgIcon ChevronRight => new ChevronRight();
        public static ISvgIcon ChevronDown => new ChevronDown();
        public static ISvgIcon ChevronLeft => new ChevronLeft();
        public static ISvgIcon ArrowUp => new ArrowUp();
        public static ISvgIcon ArrowRight => new ArrowRight();
        public static ISvgIcon ArrowDown => new ArrowDown();
        public static ISvgIcon ArrowLeft => new ArrowLeft();
        public static ISvgIcon LevelDown => new LevelDown();
        public static ISvgIcon LevelUp => new LevelUp();
        public static ISvgIcon LevelToTop => new LevelToTop();
        public static ISvgIcon ColResize => new ColResize();
        public static ISvgIcon ArrowsAxes => new ArrowsAxes();
        public static ISvgIcon ArrowsSwap => new ArrowsSwap();
        public static ISvgIcon DragAndDrop => new DragAndDrop();
        public static ISvgIcon Categorize => new Categorize();
        public static ISvgIcon Grid => new Grid();
        public static ISvgIcon GridLayout => new GridLayout();
        public static ISvgIcon Group => new Group();
        public static ISvgIcon Ungroup => new Ungroup();
        public static ISvgIcon HandleDrag => new HandleDrag();
        public static ISvgIcon Layout => new Layout();
        public static ISvgIcon Layout1By4 => new Layout1By4();
        public static ISvgIcon Layout2By2 => new Layout2By2();
        public static ISvgIcon LayoutSideBySide => new LayoutSideBySide();
        public static ISvgIcon LayoutStacked => new LayoutStacked();
        public static ISvgIcon Columns => new Columns();
        public static ISvgIcon Rows => new Rows();
        public static ISvgIcon Reorder => new Reorder();
        public static ISvgIcon Menu => new Menu();
        public static ISvgIcon MoreVertical => new MoreVertical();
        public static ISvgIcon MoreHorizontal => new MoreHorizontal();
        public static ISvgIcon Overlap => new Overlap();
        public static ISvgIcon Home => new Home();
        public static ISvgIcon ArrowsLeftRight => new ArrowsLeftRight();
        public static ISvgIcon ArrowsTopBottom => new ArrowsTopBottom();
        public static ISvgIcon BorderRadiusBottomLeft => new BorderRadiusBottomLeft();
        public static ISvgIcon BorderRadiusBottomRight => new BorderRadiusBottomRight();
        public static ISvgIcon BorderRadiusTopLeft => new BorderRadiusTopLeft();
        public static ISvgIcon BorderRadiusTopRight => new BorderRadiusTopRight();
        public static ISvgIcon BorderRadius => new BorderRadius();
        public static ISvgIcon BorderStyleBottom => new BorderStyleBottom();
        public static ISvgIcon BorderStyleLeft => new BorderStyleLeft();
        public static ISvgIcon BorderStyleRight => new BorderStyleRight();
        public static ISvgIcon BorderStyleTop => new BorderStyleTop();
        public static ISvgIcon BorderStyle => new BorderStyle();
        public static ISvgIcon BoxSizing => new BoxSizing();
        public static ISvgIcon ChevronDoubleDown => new ChevronDoubleDown();
        public static ISvgIcon ChevronDoubleLeft => new ChevronDoubleLeft();
        public static ISvgIcon ChevronDoubleRight => new ChevronDoubleRight();
        public static ISvgIcon ChevronDoubleUp => new ChevronDoubleUp();
        public static ISvgIcon DataOds => new DataOds();
        public static ISvgIcon NonRecurrence => new NonRecurrence();
        public static ISvgIcon DisplayBlock => new DisplayBlock();
        public static ISvgIcon DisplayFlex => new DisplayFlex();
        public static ISvgIcon DisplayInlineFlex => new DisplayInlineFlex();
        public static ISvgIcon DropletSlider => new DropletSlider();
        public static ISvgIcon FileReport => new FileReport();
        public static ISvgIcon GapColumn => new GapColumn();
        public static ISvgIcon GapRow => new GapRow();
        public static ISvgIcon HandleResizeAlt => new HandleResizeAlt();
        public static ISvgIcon HandleResize => new HandleResize();
        public static ISvgIcon Images => new Images();
        public static ISvgIcon LetterSpace => new LetterSpace();
        public static ISvgIcon LineHeight => new LineHeight();
        public static ISvgIcon ListLatinBig => new ListLatinBig();
        public static ISvgIcon ListLatinSmall => new ListLatinSmall();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ListRomanUpper instead.", false)]
        public static ISvgIcon ListRomanBig => new ListRomanBig();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ListRomanLower instead.", false)]
        public static ISvgIcon ListRomanSmall => new ListRomanSmall();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ListUnordered instead.", false)]
        public static ISvgIcon ListUnorderedOutline => new ListUnorderedOutline();
        public static ISvgIcon ListUnorderedSquare => new ListUnorderedSquare();
        public static ISvgIcon MaxHeight => new MaxHeight();
        public static ISvgIcon MaxWidth => new MaxWidth();
        public static ISvgIcon MinHeight => new MinHeight();
        public static ISvgIcon MinWidth => new MinWidth();
        public static ISvgIcon OutlineOffset => new OutlineOffset();
        public static ISvgIcon OutlineWidth => new OutlineWidth();
        public static ISvgIcon PaddingBottom => new PaddingBottom();
        public static ISvgIcon PaddingLeft => new PaddingLeft();
        public static ISvgIcon PaddingRight => new PaddingRight();
        public static ISvgIcon PaddingTop => new PaddingTop();
        public static ISvgIcon Padding => new Padding();
        public static ISvgIcon PositionBottom => new PositionBottom();
        public static ISvgIcon PositionLeft => new PositionLeft();
        public static ISvgIcon PositionRight => new PositionRight();
        public static ISvgIcon PositionTop => new PositionTop();
        public static ISvgIcon RegularExpression => new RegularExpression();
        public static ISvgIcon ReplaceAll => new ReplaceAll();
        public static ISvgIcon ReplaceSingle => new ReplaceSingle();
        public static ISvgIcon ReportElement => new ReportElement();
        public static ISvgIcon RightDoubleQuotes => new RightDoubleQuotes();
        public static ISvgIcon WholeWord => new WholeWord();
        public static ISvgIcon DataSds => new DataSds();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Download instead.", false)]
        public static ISvgIcon DownloadLight => new DownloadLight();
        public static ISvgIcon EyeSlash => new EyeSlash();
        public static ISvgIcon DisplayInlineBlock => new DisplayInlineBlock();
        public static ISvgIcon PaperPlane => new PaperPlane();
        public static ISvgIcon GaugeLinear => new GaugeLinear();
        public static ISvgIcon GaugeRadial => new GaugeRadial();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Envelope instead.", false)]
        public static ISvgIcon EnvelopeBox => new EnvelopeBox();
        public static ISvgIcon EnvelopeLink => new EnvelopeLink();
        public static ISvgIcon Envelope => new Envelope();
        public static ISvgIcon WarningCircle => new WarningCircle();
        public static ISvgIcon WarningTriangle => new WarningTriangle();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.InfoCircle instead.", false)]
        public static ISvgIcon InfoSolid => new InfoSolid();
        public static ISvgIcon FontGrow => new FontGrow();
        public static ISvgIcon FontShrink => new FontShrink();
        public static ISvgIcon TextOverflow => new TextOverflow();
        public static ISvgIcon TextWrapArrow => new TextWrapArrow();
        public static ISvgIcon TextTruncate => new TextTruncate();
        public static ISvgIcon TextClip => new TextClip();
        public static ISvgIcon BorderColor => new BorderColor();
        public static ISvgIcon BorderType => new BorderType();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ThumbDown instead.", false)]
        public static ISvgIcon ThumbDownOutline => new ThumbDownOutline();
        public static ISvgIcon ThumbDown => new ThumbDown();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ThumbUp instead.", false)]
        public static ISvgIcon ThumbUpOutline => new ThumbUpOutline();
        public static ISvgIcon ThumbUp => new ThumbUp();
        public static ISvgIcon Sparkles => new Sparkles();
        public static ISvgIcon ParagraphMark => new ParagraphMark();
        public static ISvgIcon ParagraphHeight => new ParagraphHeight();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.User instead.", false)]
        public static ISvgIcon UserOutline => new UserOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Wallet instead.", false)]
        public static ISvgIcon WalletSolid => new WalletSolid();
        public static ISvgIcon Stamp => new Stamp();
        public static ISvgIcon StickyNote => new StickyNote();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Ruler instead.", false)]
        public static ISvgIcon RulerOutline => new RulerOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Eraser instead.", false)]
        public static ISvgIcon EraserOutline => new EraserOutline();
        public static ISvgIcon EditAnnotations => new EditAnnotations();
        public static ISvgIcon Highlight => new Highlight();
        public static ISvgIcon HighlightFree => new HighlightFree();
        public static ISvgIcon FreeText => new FreeText();
        public static ISvgIcon XLogo => new XLogo();
        public static ISvgIcon Inputbox => new Inputbox();
        public static ISvgIcon Scale => new Scale();
        public static ISvgIcon Van => new Van();
        public static ISvgIcon Truck => new Truck();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Wallet instead.", false)]
        public static ISvgIcon WalletOutline => new WalletOutline();
        public static ISvgIcon Transactions => new Transactions();
        public static ISvgIcon HandleDragDots => new HandleDragDots();
        public static ISvgIcon ArrowDownLeft => new ArrowDownLeft();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Recycle instead.", false)]
        public static ISvgIcon RecycleSolid => new RecycleSolid();
        public static ISvgIcon IndustrialVehicle => new IndustrialVehicle();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Recycle instead.", false)]
        public static ISvgIcon RecycleOutline => new RecycleOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Plane instead.", false)]
        public static ISvgIcon PlaneSolid => new PlaneSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Plane instead.", false)]
        public static ISvgIcon PlaneOutline => new PlaneOutline();
        public static ISvgIcon MoneyExchange => new MoneyExchange();
        public static ISvgIcon Sustainability => new Sustainability();
        public static ISvgIcon Speed => new Speed();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Devices instead.", false)]
        public static ISvgIcon DevicesOutline => new DevicesOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Devices instead.", false)]
        public static ISvgIcon DevicesSolid => new DevicesSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Instagram instead.", false)]
        public static ISvgIcon InstagramBox => new InstagramBox();
        public static ISvgIcon Instagram => new Instagram();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Laptop instead.", false)]
        public static ISvgIcon LaptopOutline => new LaptopOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Laptop instead.", false)]
        public static ISvgIcon LaptopSolid => new LaptopSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.MobileRinging instead.", false)]
        public static ISvgIcon MobileOutlineRinging => new MobileOutlineRinging();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Mobile instead.", false)]
        public static ISvgIcon MobileOutline => new MobileOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.MobileRinging instead.", false)]
        public static ISvgIcon MobileSolidRinging => new MobileSolidRinging();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Mobile instead.", false)]
        public static ISvgIcon MobileSolid => new MobileSolid();
        public static ISvgIcon Locations => new Locations();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Tablet instead.", false)]
        public static ISvgIcon TabletOutline => new TabletOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Tablet instead.", false)]
        public static ISvgIcon TabletSolid => new TabletSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Users instead.", false)]
        public static ISvgIcon UsersOutline => new UsersOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Users instead.", false)]
        public static ISvgIcon UsersSolid => new UsersSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Whatsapp instead.", false)]
        public static ISvgIcon WhatsappBox => new WhatsappBox();
        public static ISvgIcon Whatsapp => new Whatsapp();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.XLogo instead.", false)]
        public static ISvgIcon XLogoBox => new XLogoBox();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Sms instead.", false)]
        public static ISvgIcon SmsOutline => new SmsOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Sms instead.", false)]
        public static ISvgIcon SmsSolid => new SmsSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Therapist instead.", false)]
        public static ISvgIcon TherapistOutline => new TherapistOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Therapist instead.", false)]
        public static ISvgIcon TherapistSolid => new TherapistSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Patient instead.", false)]
        public static ISvgIcon PatientSolid => new PatientSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Patient instead.", false)]
        public static ISvgIcon PatientOutline => new PatientOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Nurse instead.", false)]
        public static ISvgIcon NurseSolid => new NurseSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Nurse instead.", false)]
        public static ISvgIcon NurseOutline => new NurseOutline();
        public static ISvgIcon Optimization => new Optimization();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.SecurityCheck instead.", false)]
        public static ISvgIcon SecurityCheckOutline => new SecurityCheckOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.SecurityCheck instead.", false)]
        public static ISvgIcon SecurityCheckSolid => new SecurityCheckSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.SecurityLock instead.", false)]
        public static ISvgIcon SecurityLockOutline => new SecurityLockOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.SecurityLock instead.", false)]
        public static ISvgIcon SecurityLockSolid => new SecurityLockSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Upgrade instead.", false)]
        public static ISvgIcon UpgradeOutline => new UpgradeOutline();
        public static ISvgIcon UpgradeReload => new UpgradeReload();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Upgrade instead.", false)]
        public static ISvgIcon UpgradeSolid => new UpgradeSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Food instead.", false)]
        public static ISvgIcon FoodSolid => new FoodSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Food instead.", false)]
        public static ISvgIcon FoodOutline => new FoodOutline();
        public static ISvgIcon Area => new Area();
        public static ISvgIcon ArrowShape => new ArrowShape();
        public static ISvgIcon BorderRadiusUndefined => new BorderRadiusUndefined();
        public static ISvgIcon BorderWidth => new BorderWidth();
        public static ISvgIcon CircleShape => new CircleShape();
        public static ISvgIcon Combobox => new Combobox();
        public static ISvgIcon Cube => new Cube();
        public static ISvgIcon Distance => new Distance();
        public static ISvgIcon DrawFree => new DrawFree();
        public static ISvgIcon Dropdown => new Dropdown();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Eraser instead.", false)]
        public static ISvgIcon EraserSolid => new EraserSolid();
        public static ISvgIcon HexagonShape => new HexagonShape();
        public static ISvgIcon InsertFreeText => new InsertFreeText();
        public static ISvgIcon LineShape => new LineShape();
        public static ISvgIcon PasswordBox => new PasswordBox();
        public static ISvgIcon Perimeter => new Perimeter();
        public static ISvgIcon RectangleShape => new RectangleShape();
        public static ISvgIcon ReplaceFreeText => new ReplaceFreeText();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Ruler instead.", false)]
        public static ISvgIcon RulerOutlineAlt => new RulerOutlineAlt();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Ruler instead.", false)]
        public static ISvgIcon RulerSolidAlt => new RulerSolidAlt();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Ruler instead.", false)]
        public static ISvgIcon RulerSolid => new RulerSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.RulerTriangle instead.", false)]
        public static ISvgIcon RulerTriangleOutline => new RulerTriangleOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.RulerTriangle instead.", false)]
        public static ISvgIcon RulerTriangleSolid => new RulerTriangleSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.AwardNumber instead.", false)]
        public static ISvgIcon AwardNumberOutline => new AwardNumberOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.AwardNumber instead.", false)]
        public static ISvgIcon AwardNumberSolid => new AwardNumberSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.AwardTrophy instead.", false)]
        public static ISvgIcon AwardStarOutline => new AwardStarOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.AwardTrophy instead.", false)]
        public static ISvgIcon AwardStarSolid => new AwardStarSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Banknote instead.", false)]
        public static ISvgIcon BanknoteOutline => new BanknoteOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Banknote instead.", false)]
        public static ISvgIcon BanknoteSolid => new BanknoteSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Bathtub instead.", false)]
        public static ISvgIcon BathtubeOutline => new BathtubeOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Bathtub instead.", false)]
        public static ISvgIcon BathtubeSolid => new BathtubeSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Bed instead.", false)]
        public static ISvgIcon BedOutline => new BedOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Bed instead.", false)]
        public static ISvgIcon BedSolid => new BedSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Bug instead.", false)]
        public static ISvgIcon BugOutline => new BugOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Bug instead.", false)]
        public static ISvgIcon BugSolid => new BugSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Buildings instead.", false)]
        public static ISvgIcon BuildingsOutline => new BuildingsOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Buildings instead.", false)]
        public static ISvgIcon BuildingsSolid => new BuildingsSolid();
        public static ISvgIcon Bicycle => new Bicycle();
        public static ISvgIcon Bus => new Bus();
        public static ISvgIcon Car => new Car();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Dashboard instead.", false)]
        public static ISvgIcon DashboardOutline => new DashboardOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Dashboard instead.", false)]
        public static ISvgIcon DashboardSolid => new DashboardSolid();
        public static ISvgIcon Decision => new Decision();
        public static ISvgIcon Directions => new Directions();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Education instead.", false)]
        public static ISvgIcon EducationOutline => new EducationOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Education instead.", false)]
        public static ISvgIcon EducationSolid => new EducationSolid();
        public static ISvgIcon Headset => new Headset();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Luggage instead.", false)]
        public static ISvgIcon LuggageOutline => new LuggageOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Luggage instead.", false)]
        public static ISvgIcon LuggageSolid => new LuggageSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.NonStop instead.", false)]
        public static ISvgIcon NonStopOutline => new NonStopOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.NonStop instead.", false)]
        public static ISvgIcon NonStopSolid => new NonStopSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Pills instead.", false)]
        public static ISvgIcon PillsOutline => new PillsOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Pills instead.", false)]
        public static ISvgIcon PillsSolid => new PillsSolid();
        public static ISvgIcon Plan => new Plan();
        public static ISvgIcon Undo => new Undo();
        public static ISvgIcon Redo => new Redo();
        public static ISvgIcon ArrowRotateCcw => new ArrowRotateCcw();
        public static ISvgIcon ArrowRotateCw => new ArrowRotateCw();
        public static ISvgIcon ArrowsNoRepeat => new ArrowsNoRepeat();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ArrowRotateCcw instead.", false)]
        public static ISvgIcon ArrowRotateCcwSmall => new ArrowRotateCcwSmall();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ArrowRotateCw instead.", false)]
        public static ISvgIcon ArrowRotateCwSmall => new ArrowRotateCwSmall();
        public static ISvgIcon Clock => new Clock();
        public static ISvgIcon Calendar => new Calendar();
        public static ISvgIcon Save => new Save();
        public static ISvgIcon Print => new Print();
        public static ISvgIcon Pencil => new Pencil();
        public static ISvgIcon Trash => new Trash();
        public static ISvgIcon Paperclip => new Paperclip();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Paperclip instead.", false)]
        public static ISvgIcon PaperclipAlt => new PaperclipAlt();
        public static ISvgIcon Link => new Link();
        public static ISvgIcon Unlink => new Unlink();
        public static ISvgIcon LinkVertical => new LinkVertical();
        public static ISvgIcon UnlinkVertical => new UnlinkVertical();
        public static ISvgIcon Lock => new Lock();
        public static ISvgIcon Unlock => new Unlock();
        public static ISvgIcon Cancel => new Cancel();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Cancel instead.", false)]
        public static ISvgIcon CancelOutline => new CancelOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Cancel instead.", false)]
        public static ISvgIcon CancelCircle => new CancelCircle();
        public static ISvgIcon Check => new Check();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Check instead.", false)]
        public static ISvgIcon CheckOutline => new CheckOutline();
        public static ISvgIcon CheckCircle => new CheckCircle();
        public static ISvgIcon X => new X();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.X instead.", false)]
        public static ISvgIcon XOutline => new XOutline();
        public static ISvgIcon XCircle => new XCircle();
        public static ISvgIcon Plus => new Plus();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Plus instead.", false)]
        public static ISvgIcon PlusOutline => new PlusOutline();
        public static ISvgIcon PlusCircle => new PlusCircle();
        public static ISvgIcon Minus => new Minus();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Minus instead.", false)]
        public static ISvgIcon MinusOutline => new MinusOutline();
        public static ISvgIcon MinusCircle => new MinusCircle();
        public static ISvgIcon SortAsc => new SortAsc();
        public static ISvgIcon SortDesc => new SortDesc();
        public static ISvgIcon SortClear => new SortClear();
        public static ISvgIcon SortAscSmall => new SortAscSmall();
        public static ISvgIcon SortDescSmall => new SortDescSmall();
        public static ISvgIcon Filter => new Filter();
        public static ISvgIcon FilterClear => new FilterClear();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Filter instead.", false)]
        public static ISvgIcon FilterSmall => new FilterSmall();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.FilterSortAsc instead.", false)]
        public static ISvgIcon FilterSortAscSmall => new FilterSortAscSmall();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.FilterSortDesc instead.", false)]
        public static ISvgIcon FilterSortDescSmall => new FilterSortDescSmall();
        public static ISvgIcon FilterAddExpression => new FilterAddExpression();
        public static ISvgIcon FilterAddGroup => new FilterAddGroup();
        public static ISvgIcon Login => new Login();
        public static ISvgIcon Logout => new Logout();
        public static ISvgIcon Download => new Download();
        public static ISvgIcon Upload => new Upload();
        public static ISvgIcon HyperlinkOpen => new HyperlinkOpen();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.HyperlinkOpen instead.", false)]
        public static ISvgIcon HyperlinkOpenSm => new HyperlinkOpenSm();
        public static ISvgIcon Launch => new Launch();
        public static ISvgIcon Window => new Window();
        public static ISvgIcon WindowRestore => new WindowRestore();
        public static ISvgIcon WindowMinimize => new WindowMinimize();
        public static ISvgIcon Gear => new Gear();
        public static ISvgIcon Gears => new Gears();
        public static ISvgIcon Wrench => new Wrench();
        public static ISvgIcon Eye => new Eye();
        public static ISvgIcon Search => new Search();
        public static ISvgIcon ZoomIn => new ZoomIn();
        public static ISvgIcon ZoomOut => new ZoomOut();
        public static ISvgIcon ArrowsMove => new ArrowsMove();
        public static ISvgIcon Calculator => new Calculator();
        public static ISvgIcon Cart => new Cart();
        public static ISvgIcon Connector => new Connector();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Plus instead.", false)]
        public static ISvgIcon PlusSm => new PlusSm();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Minus instead.", false)]
        public static ISvgIcon MinusSm => new MinusSm();
        public static ISvgIcon KpiStatusDeny => new KpiStatusDeny();
        public static ISvgIcon KpiStatusHold => new KpiStatusHold();
        public static ISvgIcon KpiStatusOpen => new KpiStatusOpen();
        public static ISvgIcon Equal => new Equal();
        public static ISvgIcon NotEqual => new NotEqual();
        public static ISvgIcon LessOrEqual => new LessOrEqual();
        public static ISvgIcon GreaterOrEqual => new GreaterOrEqual();
        public static ISvgIcon Divide => new Divide();
        public static ISvgIcon Accessibility => new Accessibility();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Barcode instead.", false)]
        public static ISvgIcon BarcodeOutline => new BarcodeOutline();
        public static ISvgIcon Barcode => new Barcode();
        public static ISvgIcon BarcodeScanner => new BarcodeScanner();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.QrCode instead.", false)]
        public static ISvgIcon QrCodeOutline => new QrCodeOutline();
        public static ISvgIcon QrCode => new QrCode();
        public static ISvgIcon QrCodeScanner => new QrCodeScanner();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.BarcodeScanner instead.", false)]
        public static ISvgIcon BarcodeQrCodeScanner => new BarcodeQrCodeScanner();
        public static ISvgIcon Signature => new Signature();
        public static ISvgIcon Hand => new Hand();
        public static ISvgIcon Pointer => new Pointer();
        public static ISvgIcon Stick => new Stick();
        public static ISvgIcon Unstick => new Unstick();
        public static ISvgIcon SetColumnPosition => new SetColumnPosition();
        public static ISvgIcon ClockArrowRotate => new ClockArrowRotate();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.QuestionCircle instead.", false)]
        public static ISvgIcon QuestionSolid => new QuestionSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Clean instead.", false)]
        public static ISvgIcon CleanOutline => new CleanOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Clean instead.", false)]
        public static ISvgIcon CleanSolid => new CleanSolid();
        public static ISvgIcon ConcreteTruck => new ConcreteTruck();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Discount instead.", false)]
        public static ISvgIcon DiscountOutline => new DiscountOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Discount instead.", false)]
        public static ISvgIcon DiscountSolid => new DiscountSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Doctor instead.", false)]
        public static ISvgIcon DoctorOutline => new DoctorOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Doctor instead.", false)]
        public static ISvgIcon DoctorSolid => new DoctorSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.LabTechnician instead.", false)]
        public static ISvgIcon LabTechnicianOutline => new LabTechnicianOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.LabTechnician instead.", false)]
        public static ISvgIcon LabTechnicianSolid => new LabTechnicianSolid();
        public static ISvgIcon SweeperVehicle => new SweeperVehicle();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.WeightScale instead.", false)]
        public static ISvgIcon WeightScaleOutline => new WeightScaleOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.WeightScale instead.", false)]
        public static ISvgIcon WeightScaleSolid => new WeightScaleSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Microphone instead.", false)]
        public static ISvgIcon MicrophoneSolid => new MicrophoneSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Microphone instead.", false)]
        public static ISvgIcon MicrophoneOutline => new MicrophoneOutline();
        public static ISvgIcon RowExpand => new RowExpand();
        public static ISvgIcon RowCollapse => new RowCollapse();
        public static ISvgIcon MenuFilter => new MenuFilter();
        public static ISvgIcon MenuSortAsc => new MenuSortAsc();
        public static ISvgIcon MenuSortDesc => new MenuSortDesc();
        public static ISvgIcon PasteSparkle => new PasteSparkle();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Pin instead.", false)]
        public static ISvgIcon PinSolid => new PinSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Pin instead.", false)]
        public static ISvgIcon PinOutline => new PinOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Unpin instead.", false)]
        public static ISvgIcon UnpinSolid => new UnpinSolid();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Unpin instead.", false)]
        public static ISvgIcon UnpinOutline => new UnpinOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.PinTop instead.", false)]
        public static ISvgIcon PinOutlineTop => new PinOutlineTop();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.PinBottom instead.", false)]
        public static ISvgIcon PinOutlineBottom => new PinOutlineBottom();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ArrowDown instead.", false)]
        public static ISvgIcon ArrowDownOutline => new ArrowDownOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ArrowRotateCw instead.", false)]
        public static ISvgIcon ArrowRotateCwOutline => new ArrowRotateCwOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ArrowUp instead.", false)]
        public static ISvgIcon ArrowUpOutline => new ArrowUpOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ArrowsRotate instead.", false)]
        public static ISvgIcon ArrowsRotateOutline => new ArrowsRotateOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.FileClock instead.", false)]
        public static ISvgIcon FileClockOutline => new FileClockOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Lightbulb instead.", false)]
        public static ISvgIcon LightbulbOutline => new LightbulbOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Paperclip instead.", false)]
        public static ISvgIcon PaperclipOutlineAltRight => new PaperclipOutlineAltRight();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Paperclip instead.", false)]
        public static ISvgIcon PaperclipOutline => new PaperclipOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.XCircle instead.", false)]
        public static ISvgIcon XMarkOutline => new XMarkOutline();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.XCircle instead.", false)]
        public static ISvgIcon XMarkSmOutline => new XMarkSmOutline();
        public static ISvgIcon ZoomSparkle => new ZoomSparkle();
        public static ISvgIcon Play => new Play();
        public static ISvgIcon Pause => new Pause();
        public static ISvgIcon Stop => new Stop();
        public static ISvgIcon Rewind => new Rewind();
        public static ISvgIcon Forward => new Forward();
        public static ISvgIcon VolumeDown => new VolumeDown();
        public static ISvgIcon VolumeUp => new VolumeUp();
        public static ISvgIcon VolumeMute => new VolumeMute();
        public static ISvgIcon Hd => new Hd();
        public static ISvgIcon ClosedCaptions => new ClosedCaptions();
        public static ISvgIcon Playlist => new Playlist();
        public static ISvgIcon MusicNotes => new MusicNotes();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Play instead.", false)]
        public static ISvgIcon PlaySm => new PlaySm();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Pause instead.", false)]
        public static ISvgIcon PauseSm => new PauseSm();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Stop instead.", false)]
        public static ISvgIcon StopSm => new StopSm();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Heart instead.", false)]
        public static ISvgIcon HeartOutline => new HeartOutline();
        public static ISvgIcon Heart => new Heart();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Star instead.", false)]
        public static ISvgIcon StarOutline => new StarOutline();
        public static ISvgIcon Star => new Star();
        public static ISvgIcon Checkbox => new Checkbox();
        public static ISvgIcon CheckboxChecked => new CheckboxChecked();
        public static ISvgIcon CheckboxIndeterminate => new CheckboxIndeterminate();
        public static ISvgIcon CheckboxNull => new CheckboxNull();
        public static ISvgIcon Circle => new Circle();
        public static ISvgIcon Radiobutton => new Radiobutton();
        public static ISvgIcon RadiobuttonChecked => new RadiobuttonChecked();
        public static ISvgIcon Bell => new Bell();
        public static ISvgIcon InfoCircle => new InfoCircle();
        public static ISvgIcon QuestionCircle => new QuestionCircle();
        public static ISvgIcon ExclamationCircle => new ExclamationCircle();
        public static ISvgIcon Camera => new Camera();
        public static ISvgIcon Image => new Image();
        public static ISvgIcon ImageExport => new ImageExport();
        public static ISvgIcon ZoomActualSize => new ZoomActualSize();
        public static ISvgIcon ZoomBestFit => new ZoomBestFit();
        public static ISvgIcon ImageResize => new ImageResize();
        public static ISvgIcon Crop => new Crop();
        public static ISvgIcon Mirror => new Mirror();
        public static ISvgIcon FlipHorizontal => new FlipHorizontal();
        public static ISvgIcon FlipVertical => new FlipVertical();
        public static ISvgIcon Rotate => new Rotate();
        public static ISvgIcon RotateRight => new RotateRight();
        public static ISvgIcon RotateLeft => new RotateLeft();
        public static ISvgIcon Brush => new Brush();
        public static ISvgIcon Palette => new Palette();
        public static ISvgIcon Droplet => new Droplet();
        public static ISvgIcon ShapeLine => new ShapeLine();
        public static ISvgIcon BrightnessContrast => new BrightnessContrast();
        public static ISvgIcon Sliders => new Sliders();
        public static ISvgIcon InvertColors => new InvertColors();
        public static ISvgIcon Transparency => new Transparency();
        public static ISvgIcon Grayscale => new Grayscale();
        public static ISvgIcon Blur => new Blur();
        public static ISvgIcon Sharpen => new Sharpen();
        public static ISvgIcon Shapes => new Shapes();
        public static ISvgIcon RoundCorners => new RoundCorners();
        public static ISvgIcon BringToFront => new BringToFront();
        public static ISvgIcon BringToBack => new BringToBack();
        public static ISvgIcon BringForward => new BringForward();
        public static ISvgIcon BringBackward => new BringBackward();
        public static ISvgIcon AlignSelfStart => new AlignSelfStart();
        public static ISvgIcon AlignSelfCenter => new AlignSelfCenter();
        public static ISvgIcon AlignSelfEnd => new AlignSelfEnd();
        public static ISvgIcon AlignSelfStartAlt => new AlignSelfStartAlt();
        public static ISvgIcon AlignSelfCenterAlt => new AlignSelfCenterAlt();
        public static ISvgIcon AlignSelfEndAlt => new AlignSelfEndAlt();
        public static ISvgIcon ThumbnailsUp => new ThumbnailsUp();
        public static ISvgIcon ThumbnailsRight => new ThumbnailsRight();
        public static ISvgIcon ThumbnailsDown => new ThumbnailsDown();
        public static ISvgIcon ThumbnailsLeft => new ThumbnailsLeft();
        public static ISvgIcon Fullscreen => new Fullscreen();
        public static ISvgIcon FullscreenExit => new FullscreenExit();
        public static ISvgIcon DropletSlash => new DropletSlash();
        public static ISvgIcon Photos => new Photos();
        public static ISvgIcon AlignToGrid => new AlignToGrid();
        public static ISvgIcon SizeToGrid => new SizeToGrid();
        public static ISvgIcon MakeSameSize => new MakeSameSize();
        public static ISvgIcon MakeSameWidth => new MakeSameWidth();
        public static ISvgIcon MakeSameHeight => new MakeSameHeight();
        public static ISvgIcon MakeHorizontalSpacingEqual => new MakeHorizontalSpacingEqual();
        public static ISvgIcon IncreaseHorizontalSpacing => new IncreaseHorizontalSpacing();
        public static ISvgIcon DecreaseHorizontalSpacing => new DecreaseHorizontalSpacing();
        public static ISvgIcon RemoveHorizontalSpacing => new RemoveHorizontalSpacing();
        public static ISvgIcon MakeVerticalSpacingEqual => new MakeVerticalSpacingEqual();
        public static ISvgIcon IncreaseVerticalSpacing => new IncreaseVerticalSpacing();
        public static ISvgIcon DecreaseVerticalSpacing => new DecreaseVerticalSpacing();
        public static ISvgIcon RemoveVerticalSpacing => new RemoveVerticalSpacing();
        public static ISvgIcon Eyedropper => new Eyedropper();
        public static ISvgIcon SnapGrid => new SnapGrid();
        public static ISvgIcon SnapToGridlines => new SnapToGridlines();
        public static ISvgIcon SnapToSnaplines => new SnapToSnaplines();
        public static ISvgIcon Dimensions => new Dimensions();
        public static ISvgIcon AlignSelfStretch => new AlignSelfStretch();
        public static ISvgIcon AlignSelfStretchAlt => new AlignSelfStretchAlt();
        public static ISvgIcon AlignItemsStart => new AlignItemsStart();
        public static ISvgIcon AlignItemsCenter => new AlignItemsCenter();
        public static ISvgIcon AlignItemsEnd => new AlignItemsEnd();
        public static ISvgIcon AlignItemsStretch => new AlignItemsStretch();
        public static ISvgIcon AlignItemsBaseline => new AlignItemsBaseline();
        public static ISvgIcon AlignItemsStartAlt => new AlignItemsStartAlt();
        public static ISvgIcon AlignItemsCenterAlt => new AlignItemsCenterAlt();
        public static ISvgIcon AlignItemsEndAlt => new AlignItemsEndAlt();
        public static ISvgIcon AlignItemsStretchAlt => new AlignItemsStretchAlt();
        public static ISvgIcon AlignItemsBaselineAlt => new AlignItemsBaselineAlt();
        public static ISvgIcon JustifyContentStart => new JustifyContentStart();
        public static ISvgIcon JustifyContentCenter => new JustifyContentCenter();
        public static ISvgIcon JustifyContentEnd => new JustifyContentEnd();
        public static ISvgIcon JustifyContentBetween => new JustifyContentBetween();
        public static ISvgIcon JustifyContentAround => new JustifyContentAround();
        public static ISvgIcon JustifyContentStartAlt => new JustifyContentStartAlt();
        public static ISvgIcon JustifyContentCenterAlt => new JustifyContentCenterAlt();
        public static ISvgIcon JustifyContentEndAlt => new JustifyContentEndAlt();
        public static ISvgIcon JustifyContentBetweenAlt => new JustifyContentBetweenAlt();
        public static ISvgIcon JustifyContentAroundAlt => new JustifyContentAroundAlt();
        public static ISvgIcon FileWrench => new FileWrench();
        public static ISvgIcon Bold => new Bold();
        public static ISvgIcon Italic => new Italic();
        public static ISvgIcon Underline => new Underline();
        public static ISvgIcon FontFamily => new FontFamily();
        public static ISvgIcon ForegroundColor => new ForegroundColor();
        public static ISvgIcon ConvertLowercase => new ConvertLowercase();
        public static ISvgIcon ConvertUppercase => new ConvertUppercase();
        public static ISvgIcon Strikethrough => new Strikethrough();
        public static ISvgIcon Subscript => new Subscript();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Superscript instead.", false)]
        public static ISvgIcon Supscript => new Supscript();
        public static ISvgIcon Div => new Div();
        public static ISvgIcon All => new All();
        public static ISvgIcon H1 => new H1();
        public static ISvgIcon H2 => new H2();
        public static ISvgIcon H3 => new H3();
        public static ISvgIcon H4 => new H4();
        public static ISvgIcon H5 => new H5();
        public static ISvgIcon H6 => new H6();
        public static ISvgIcon ListOrdered => new ListOrdered();
        public static ISvgIcon ListUnordered => new ListUnordered();
        public static ISvgIcon Indent => new Indent();
        public static ISvgIcon Outdent => new Outdent();
        public static ISvgIcon InsertTop => new InsertTop();
        public static ISvgIcon InsertMiddle => new InsertMiddle();
        public static ISvgIcon InsertBottom => new InsertBottom();
        public static ISvgIcon AlignTop => new AlignTop();
        public static ISvgIcon AlignMiddle => new AlignMiddle();
        public static ISvgIcon AlignBottom => new AlignBottom();
        public static ISvgIcon AlignLeft => new AlignLeft();
        public static ISvgIcon AlignCenter => new AlignCenter();
        public static ISvgIcon AlignRight => new AlignRight();
        public static ISvgIcon AlignJustify => new AlignJustify();
        public static ISvgIcon AlignRemove => new AlignRemove();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.TextWrapArrow instead.", false)]
        public static ISvgIcon TextWrap => new TextWrap();
        public static ISvgIcon HorizontalRule => new HorizontalRule();
        public static ISvgIcon TableAlignTopLeft => new TableAlignTopLeft();
        public static ISvgIcon TableAlignTopCenter => new TableAlignTopCenter();
        public static ISvgIcon TableAlignTopRight => new TableAlignTopRight();
        public static ISvgIcon TableAlignMiddleLeft => new TableAlignMiddleLeft();
        public static ISvgIcon TableAlignMiddleCenter => new TableAlignMiddleCenter();
        public static ISvgIcon TableAlignMiddleRight => new TableAlignMiddleRight();
        public static ISvgIcon TableAlignBottomLeft => new TableAlignBottomLeft();
        public static ISvgIcon TableAlignBottomCenter => new TableAlignBottomCenter();
        public static ISvgIcon TableAlignBottomRight => new TableAlignBottomRight();
        public static ISvgIcon TableAlignRemove => new TableAlignRemove();
        public static ISvgIcon BordersAll => new BordersAll();
        public static ISvgIcon BordersOutside => new BordersOutside();
        public static ISvgIcon BordersInside => new BordersInside();
        public static ISvgIcon BordersInsideHorizontal => new BordersInsideHorizontal();
        public static ISvgIcon BordersInsideVertical => new BordersInsideVertical();
        public static ISvgIcon BorderTop => new BorderTop();
        public static ISvgIcon BorderBottom => new BorderBottom();
        public static ISvgIcon BorderLeft => new BorderLeft();
        public static ISvgIcon BorderRight => new BorderRight();
        public static ISvgIcon BordersNone => new BordersNone();
        public static ISvgIcon BordersShowHide => new BordersShowHide();
        public static ISvgIcon Form => new Form();
        public static ISvgIcon FormElement => new FormElement();
        public static ISvgIcon CodeSnippet => new CodeSnippet();
        public static ISvgIcon SelectAll => new SelectAll();
        public static ISvgIcon Button => new Button();
        public static ISvgIcon SelectBox => new SelectBox();
        public static ISvgIcon CalendarDate => new CalendarDate();
        public static ISvgIcon GroupBox => new GroupBox();
        public static ISvgIcon Textarea => new Textarea();
        public static ISvgIcon Textbox => new Textbox();
        public static ISvgIcon TextboxHidden => new TextboxHidden();
        public static ISvgIcon Password => new Password();
        public static ISvgIcon ParagraphAdd => new ParagraphAdd();
        public static ISvgIcon EditTools => new EditTools();
        public static ISvgIcon TemplateManager => new TemplateManager();
        public static ISvgIcon ChangeManually => new ChangeManually();
        public static ISvgIcon TrackChanges => new TrackChanges();
        public static ISvgIcon TrackChangesEnable => new TrackChangesEnable();
        public static ISvgIcon TrackChangesAccept => new TrackChangesAccept();
        public static ISvgIcon TrackChangesAcceptAll => new TrackChangesAcceptAll();
        public static ISvgIcon TrackChangesReject => new TrackChangesReject();
        public static ISvgIcon TrackChangesRejectAll => new TrackChangesRejectAll();
        public static ISvgIcon DocumentManager => new DocumentManager();
        public static ISvgIcon CustomIcon => new CustomIcon();
        public static ISvgIcon Book => new Book();
        public static ISvgIcon ImageAdd => new ImageAdd();
        public static ISvgIcon ImageEdit => new ImageEdit();
        public static ISvgIcon ImageMapEditor => new ImageMapEditor();
        public static ISvgIcon Comment => new Comment();
        public static ISvgIcon CommentRemove => new CommentRemove();
        public static ISvgIcon CommentsRemove => new CommentsRemove();
        [System.Obsolete("since v4. Will be removed in v5. This icon will be removed without a replacement.", false)]
        public static ISvgIcon Silverlight => new Silverlight();
        public static ISvgIcon MediaManager => new MediaManager();
        public static ISvgIcon VideoExternal => new VideoExternal();
        [System.Obsolete("since v4. Will be removed in v5. This icon will be removed without a replacement.", false)]
        public static ISvgIcon FlashManager => new FlashManager();
        public static ISvgIcon Binoculars => new Binoculars();
        public static ISvgIcon Copy => new Copy();
        public static ISvgIcon Cut => new Cut();
        public static ISvgIcon Clipboard => new Clipboard();
        public static ISvgIcon ClipboardCode => new ClipboardCode();
        public static ISvgIcon ClipboardWord => new ClipboardWord();
        public static ISvgIcon ClipboardWordAlt => new ClipboardWordAlt();
        public static ISvgIcon ClipboardHtml => new ClipboardHtml();
        public static ISvgIcon ClipboardMarkdown => new ClipboardMarkdown();
        public static ISvgIcon ClipboardText => new ClipboardText();
        public static ISvgIcon ApplyFormat => new ApplyFormat();
        public static ISvgIcon ClearCss => new ClearCss();
        public static ISvgIcon CopyFormat => new CopyFormat();
        public static ISvgIcon StripAllFormatting => new StripAllFormatting();
        public static ISvgIcon StripCssFormat => new StripCssFormat();
        public static ISvgIcon StripFontElements => new StripFontElements();
        public static ISvgIcon StripSpanElements => new StripSpanElements();
        public static ISvgIcon StripWordFormatting => new StripWordFormatting();
        public static ISvgIcon FormatCodeBlock => new FormatCodeBlock();
        public static ISvgIcon BuildingBlocks => new BuildingBlocks();
        public static ISvgIcon PuzzlePiece => new PuzzlePiece();
        public static ISvgIcon LinkAdd => new LinkAdd();
        public static ISvgIcon GlobeLink => new GlobeLink();
        public static ISvgIcon GlobeUnlink => new GlobeUnlink();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.EnvelopeLink instead.", false)]
        public static ISvgIcon EnvelopLink => new EnvelopLink();
        public static ISvgIcon Anchor => new Anchor();
        public static ISvgIcon TableAdd => new TableAdd();
        public static ISvgIcon Table => new Table();
        public static ISvgIcon TableProperties => new TableProperties();
        public static ISvgIcon TableCell => new TableCell();
        public static ISvgIcon TableCellProperties => new TableCellProperties();
        public static ISvgIcon TableColumnInsertLeft => new TableColumnInsertLeft();
        public static ISvgIcon TableColumnInsertRight => new TableColumnInsertRight();
        public static ISvgIcon TableRowInsertAbove => new TableRowInsertAbove();
        public static ISvgIcon TableRowInsertBelow => new TableRowInsertBelow();
        public static ISvgIcon TableColumnDelete => new TableColumnDelete();
        public static ISvgIcon TableRowDelete => new TableRowDelete();
        public static ISvgIcon TableCellDelete => new TableCellDelete();
        public static ISvgIcon TableDelete => new TableDelete();
        public static ISvgIcon CellsMerge => new CellsMerge();
        public static ISvgIcon CellsMergeHorizontally => new CellsMergeHorizontally();
        public static ISvgIcon CellsMergeVertically => new CellsMergeVertically();
        public static ISvgIcon CellSplitHorizontally => new CellSplitHorizontally();
        public static ISvgIcon CellSplitVertically => new CellSplitVertically();
        public static ISvgIcon TableUnmerge => new TableUnmerge();
        public static ISvgIcon PaneFreeze => new PaneFreeze();
        public static ISvgIcon RowFreeze => new RowFreeze();
        public static ISvgIcon ColumnFreeze => new ColumnFreeze();
        public static ISvgIcon ToolbarFloat => new ToolbarFloat();
        public static ISvgIcon SpellChecker => new SpellChecker();
        public static ISvgIcon ValidationXhtml => new ValidationXhtml();
        public static ISvgIcon ValidationData => new ValidationData();
        public static ISvgIcon ToggleFullScreenMode => new ToggleFullScreenMode();
        public static ISvgIcon FormulaFx => new FormulaFx();
        public static ISvgIcon Sum => new Sum();
        public static ISvgIcon Symbol => new Symbol();
        public static ISvgIcon Dollar => new Dollar();
        public static ISvgIcon Percent => new Percent();
        public static ISvgIcon CustomFormat => new CustomFormat();
        public static ISvgIcon DecimalIncrease => new DecimalIncrease();
        public static ISvgIcon DecimalDecrease => new DecimalDecrease();
        public static ISvgIcon FontSize => new FontSize();
        public static ISvgIcon ImageAbsolutePosition => new ImageAbsolutePosition();
        public static ISvgIcon TableWizard => new TableWizard();
        public static ISvgIcon Crosstab => new Crosstab();
        public static ISvgIcon CrosstabWizard => new CrosstabWizard();
        public static ISvgIcon TableBody => new TableBody();
        public static ISvgIcon TableColumnGroups => new TableColumnGroups();
        public static ISvgIcon TableCorner => new TableCorner();
        public static ISvgIcon TableRowGroups => new TableRowGroups();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Globe instead.", false)]
        public static ISvgIcon GlobeOutline => new GlobeOutline();
        public static ISvgIcon Globe => new Globe();
        public static ISvgIcon MapMarker => new MapMarker();
        public static ISvgIcon MapMarkerTarget => new MapMarkerTarget();
        public static ISvgIcon Pin => new Pin();
        public static ISvgIcon Unpin => new Unpin();
        public static ISvgIcon Share => new Share();
        public static ISvgIcon User => new User();
        public static ISvgIcon Inbox => new Inbox();
        [System.Obsolete("since v4. Will be removed in v5. This icon will be removed without a replacement.", false)]
        public static ISvgIcon Blogger => new Blogger();
        [System.Obsolete("since v4. Will be removed in v5. This icon will be removed without a replacement.", false)]
        public static ISvgIcon BloggerBox => new BloggerBox();
        public static ISvgIcon Delicious => new Delicious();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Delicious instead.", false)]
        public static ISvgIcon DeliciousBox => new DeliciousBox();
        public static ISvgIcon Digg => new Digg();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Digg instead.", false)]
        public static ISvgIcon DiggBox => new DiggBox();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Envelope instead.", false)]
        public static ISvgIcon Envelop => new Envelop();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Envelope instead.", false)]
        public static ISvgIcon EnvelopBox => new EnvelopBox();
        public static ISvgIcon Facebook => new Facebook();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Facebook instead.", false)]
        public static ISvgIcon FacebookBox => new FacebookBox();
        public static ISvgIcon Google => new Google();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Google instead.", false)]
        public static ISvgIcon GoogleBox => new GoogleBox();
        public static ISvgIcon GooglePlus => new GooglePlus();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.GooglePlus instead.", false)]
        public static ISvgIcon GooglePlusBox => new GooglePlusBox();
        public static ISvgIcon Linkedin => new Linkedin();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Linkedin instead.", false)]
        public static ISvgIcon LinkedinBox => new LinkedinBox();
        public static ISvgIcon Myspace => new Myspace();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Myspace instead.", false)]
        public static ISvgIcon MyspaceBox => new MyspaceBox();
        public static ISvgIcon Pinterest => new Pinterest();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Pinterest instead.", false)]
        public static ISvgIcon PinterestBox => new PinterestBox();
        public static ISvgIcon Reddit => new Reddit();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Reddit instead.", false)]
        public static ISvgIcon RedditBox => new RedditBox();
        public static ISvgIcon StumbleUpon => new StumbleUpon();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.StumbleUpon instead.", false)]
        public static ISvgIcon StumbleUponBox => new StumbleUponBox();
        public static ISvgIcon TellAFriend => new TellAFriend();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.TellAFriend instead.", false)]
        public static ISvgIcon TellAFriendBox => new TellAFriendBox();
        public static ISvgIcon Tumblr => new Tumblr();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Tumblr instead.", false)]
        public static ISvgIcon TumblrBox => new TumblrBox();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.XLogo instead.", false)]
        public static ISvgIcon Twitter => new Twitter();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.XLogo instead.", false)]
        public static ISvgIcon TwitterBox => new TwitterBox();
        public static ISvgIcon Yammer => new Yammer();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Yammer instead.", false)]
        public static ISvgIcon YammerBox => new YammerBox();
        public static ISvgIcon Behance => new Behance();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Behance instead.", false)]
        public static ISvgIcon BehanceBox => new BehanceBox();
        public static ISvgIcon Dribbble => new Dribbble();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Dribbble instead.", false)]
        public static ISvgIcon DribbbleBox => new DribbbleBox();
        public static ISvgIcon Rss => new Rss();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Rss instead.", false)]
        public static ISvgIcon RssBox => new RssBox();
        public static ISvgIcon Vimeo => new Vimeo();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Vimeo instead.", false)]
        public static ISvgIcon VimeoBox => new VimeoBox();
        public static ISvgIcon Youtube => new Youtube();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.Youtube instead.", false)]
        public static ISvgIcon YoutubeBox => new YoutubeBox();
        public static ISvgIcon Folder => new Folder();
        public static ISvgIcon FolderOpen => new FolderOpen();
        public static ISvgIcon FolderAdd => new FolderAdd();
        public static ISvgIcon FolderUp => new FolderUp();
        public static ISvgIcon FolderMore => new FolderMore();
        public static ISvgIcon AggregateFields => new AggregateFields();
        public static ISvgIcon File => new File();
        public static ISvgIcon FileAdd => new FileAdd();
        public static ISvgIcon FileTxt => new FileTxt();
        public static ISvgIcon FileCsv => new FileCsv();
        public static ISvgIcon FileExcel => new FileExcel();
        public static ISvgIcon FileWord => new FileWord();
        public static ISvgIcon FileMdb => new FileMdb();
        public static ISvgIcon FilePpt => new FilePpt();
        public static ISvgIcon FilePdf => new FilePdf();
        public static ISvgIcon FilePsd => new FilePsd();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.File instead.", false)]
        public static ISvgIcon FileFlash => new FileFlash();
        public static ISvgIcon FileConfig => new FileConfig();
        public static ISvgIcon FileAscx => new FileAscx();
        public static ISvgIcon FileBac => new FileBac();
        public static ISvgIcon FileZip => new FileZip();
        public static ISvgIcon Film => new Film();
        public static ISvgIcon Css3 => new Css3();
        public static ISvgIcon Html5 => new Html5();
        public static ISvgIcon Code => new Code();
        public static ISvgIcon Css => new Css();
        public static ISvgIcon Js => new Js();
        public static ISvgIcon Exe => new Exe();
        public static ISvgIcon Csproj => new Csproj();
        public static ISvgIcon Vbproj => new Vbproj();
        public static ISvgIcon Cs => new Cs();
        public static ISvgIcon Vb => new Vb();
        public static ISvgIcon Sln => new Sln();
        public static ISvgIcon Cloud => new Cloud();
        public static ISvgIcon FileHorizontal => new FileHorizontal();
        public static ISvgIcon Subreport => new Subreport();
        public static ISvgIcon Data => new Data();
        public static ISvgIcon FileHeader => new FileHeader();
        public static ISvgIcon FileFooter => new FileFooter();
        public static ISvgIcon GroupHeaderSection => new GroupHeaderSection();
        public static ISvgIcon GroupFooterSection => new GroupFooterSection();
        public static ISvgIcon PageHeaderSection => new PageHeaderSection();
        public static ISvgIcon PageFooterSection => new PageFooterSection();
        public static ISvgIcon DetailSection => new DetailSection();
        public static ISvgIcon TocSection => new TocSection();
        public static ISvgIcon GroupSection => new GroupSection();
        public static ISvgIcon Parameters => new Parameters();
        public static ISvgIcon DataCsv => new DataCsv();
        public static ISvgIcon DataJson => new DataJson();
        public static ISvgIcon DataSql => new DataSql();
        public static ISvgIcon DataWeb => new DataWeb();
        public static ISvgIcon GroupCollection => new GroupCollection();
        public static ISvgIcon ParameterBoolean => new ParameterBoolean();
        public static ISvgIcon ParameterDateTime => new ParameterDateTime();
        public static ISvgIcon ParameterFloat => new ParameterFloat();
        public static ISvgIcon ParameterInteger => new ParameterInteger();
        public static ISvgIcon ParameterString => new ParameterString();
        public static ISvgIcon TocSectionLevel => new TocSectionLevel();
        public static ISvgIcon Inherited => new Inherited();
        public static ISvgIcon FileVideo => new FileVideo();
        public static ISvgIcon FileAudio => new FileAudio();
        public static ISvgIcon FileImage => new FileImage();
        public static ISvgIcon FilePresentation => new FilePresentation();
        public static ISvgIcon FileData => new FileData();
        public static ISvgIcon FileDiscImage => new FileDiscImage();
        public static ISvgIcon FileProgramming => new FileProgramming();
        public static ISvgIcon ParametersByteArray => new ParametersByteArray();
        public static ISvgIcon ParametersUnknown => new ParametersUnknown();
        public static ISvgIcon FileError => new FileError();
        public static ISvgIcon FilesError => new FilesError();
        public static ISvgIcon DataRest => new DataRest();
        public static ISvgIcon FileTypescript => new FileTypescript();
        public static ISvgIcon TablePositionStart => new TablePositionStart();
        public static ISvgIcon TablePositionCenter => new TablePositionCenter();
        public static ISvgIcon TablePositionEnd => new TablePositionEnd();
        public static ISvgIcon ListRomanUpper => new ListRomanUpper();
        public static ISvgIcon ListRomanLower => new ListRomanLower();
        public static ISvgIcon Import => new Import();
        public static ISvgIcon Export => new Export();
        public static ISvgIcon Graph => new Graph();
        public static ISvgIcon ChartColumnClustered => new ChartColumnClustered();
        public static ISvgIcon ChartColumnStacked => new ChartColumnStacked();
        public static ISvgIcon ChartColumnStacked100 => new ChartColumnStacked100();
        public static ISvgIcon ChartColumnRange => new ChartColumnRange();
        public static ISvgIcon ChartBarClustered => new ChartBarClustered();
        public static ISvgIcon ChartBarStacked => new ChartBarStacked();
        public static ISvgIcon ChartBarStacked100 => new ChartBarStacked100();
        public static ISvgIcon ChartBarRange => new ChartBarRange();
        public static ISvgIcon ChartAreaClustered => new ChartAreaClustered();
        public static ISvgIcon ChartAreaStacked => new ChartAreaStacked();
        public static ISvgIcon ChartAreaStacked100 => new ChartAreaStacked100();
        public static ISvgIcon ChartAreaRange => new ChartAreaRange();
        public static ISvgIcon ChartLine => new ChartLine();
        public static ISvgIcon ChartLineStacked => new ChartLineStacked();
        public static ISvgIcon ChartLineStacked100 => new ChartLineStacked100();
        public static ISvgIcon ChartLineMarkers => new ChartLineMarkers();
        public static ISvgIcon ChartLineStackedMarkers => new ChartLineStackedMarkers();
        public static ISvgIcon ChartLineStacked100Markers => new ChartLineStacked100Markers();
        public static ISvgIcon ChartPie => new ChartPie();
        public static ISvgIcon ChartDoughnut => new ChartDoughnut();
        public static ISvgIcon ChartScatter => new ChartScatter();
        public static ISvgIcon ChartScatterSmoothLinesMarkers => new ChartScatterSmoothLinesMarkers();
        public static ISvgIcon ChartScatterSmoothLines => new ChartScatterSmoothLines();
        public static ISvgIcon ChartScatterStraightLinesMarkers => new ChartScatterStraightLinesMarkers();
        public static ISvgIcon ChartScatterStraightLines => new ChartScatterStraightLines();
        public static ISvgIcon ChartBubble => new ChartBubble();
        public static ISvgIcon ChartCandlestick => new ChartCandlestick();
        public static ISvgIcon ChartOhlc => new ChartOhlc();
        public static ISvgIcon ChartRadar => new ChartRadar();
        public static ISvgIcon ChartRadarMarkers => new ChartRadarMarkers();
        [System.Obsolete("since v4. Will be removed in v5. Use SvgIcon.ChartRadar instead.", false)]
        public static ISvgIcon ChartRadarFilled => new ChartRadarFilled();
        public static ISvgIcon ChartRose => new ChartRose();
        public static ISvgIcon ChartChoropleth => new ChartChoropleth();

        // Alias re-exports: unsuffixed names pointing to -outline icons
        public static ISvgIcon ArrowsRotate => ArrowsRotateOutline;
        public static ISvgIcon AwardNumber => AwardNumberOutline;
        public static ISvgIcon AwardStar => AwardStarOutline;
        public static ISvgIcon AwardTrophy => AwardStarSolid;
        public static ISvgIcon Banknote => BanknoteOutline;
        public static ISvgIcon Bed => BedOutline;
        public static ISvgIcon Bug => BugOutline;
        public static ISvgIcon Buildings => BuildingsOutline;
        public static ISvgIcon Clean => CleanOutline;
        public static ISvgIcon Dashboard => DashboardOutline;
        public static ISvgIcon Devices => DevicesOutline;
        public static ISvgIcon Discount => DiscountOutline;
        public static ISvgIcon Doctor => DoctorOutline;
        public static ISvgIcon Education => EducationOutline;
        public static ISvgIcon Eraser => EraserOutline;
        public static ISvgIcon FileClock => FileClockOutline;
        public static ISvgIcon Food => FoodOutline;
        public static ISvgIcon LabTechnician => LabTechnicianOutline;
        public static ISvgIcon Laptop => LaptopOutline;
        public static ISvgIcon Lightbulb => LightbulbOutline;
        public static ISvgIcon Luggage => LuggageOutline;
        public static ISvgIcon Microphone => MicrophoneOutline;
        public static ISvgIcon Mobile => MobileOutline;
        public static ISvgIcon NonStop => NonStopOutline;
        public static ISvgIcon Nurse => NurseOutline;
        public static ISvgIcon Patient => PatientOutline;
        public static ISvgIcon Pills => PillsOutline;
        public static ISvgIcon PinBottom => PinOutlineBottom;
        public static ISvgIcon PinTop => PinOutlineTop;
        public static ISvgIcon Plane => PlaneOutline;
        public static ISvgIcon Recycle => RecycleOutline;
        public static ISvgIcon Ruler => RulerOutlineAlt;
        public static ISvgIcon RulerTriangle => RulerTriangleOutline;
        public static ISvgIcon SecurityCheck => SecurityCheckOutline;
        public static ISvgIcon SecurityLock => SecurityLockOutline;
        public static ISvgIcon Sms => SmsOutline;
        public static ISvgIcon Tablet => TabletOutline;
        public static ISvgIcon Therapist => TherapistOutline;
        public static ISvgIcon Upgrade => UpgradeOutline;
        public static ISvgIcon Users => UsersOutline;
        public static ISvgIcon Wallet => WalletOutline;
        public static ISvgIcon WeightScale => WeightScaleOutline;
        public static ISvgIcon XMark => XMarkOutline;
        public static ISvgIcon MobileRinging => MobileOutlineRinging;
        public static ISvgIcon Bathtub => BathtubeOutline;
        public static ISvgIcon FilterSortAsc => FilterSortAscSmall;
        public static ISvgIcon FilterSortDesc => FilterSortDescSmall;
        public static ISvgIcon Superscript => Supscript;
    }
}
