module.exports = {
    multipass: true,
    floatPrecision: 4,
    js2svg: {
        pretty: true
    },
    plugins: [
        'cleanupAttrs',
        'cleanupEnableBackground',
        'cleanupIDs',
        'cleanupListOfValues',
        'cleanupNumericValues',
        'collapseGroups',
        'convertColors',
        'convertPathData',
        'convertTransform',
        'convertShapeToPath',
        'convertStyleToAttrs',
        'mergePaths',
        'minifyStyles',
        'moveElemsAttrsToGroup',
        'moveGroupAttrsToElems',
        'removeDoctype',
        'removeXMLProcInst',
        'removeComments',
        'removeMetadata',
        'removeTitle',
        'removeDesc',
        'removeUselessDefs',
        'removeXMLNS',
        'removeEditorsNSData',
        'removeEmptyAttrs',
        'removeHiddenElems',
        'removeEmptyText',
        'removeEmptyContainers',
        'removeViewBox',
        'removeUnknownsAndDefaults',
        'removeNonInheritableGroupAttrs',
        {
            removeUselessStrokeAndFill: {
                // https://github.com/svg/svgo/issues/727#issuecomment-303115276
                removeNone: true,
            },
        },
        'removeUnusedNS',
        'removeRasterImages',
        'removeDimensions',
        { removeAttrs: { attrs: '(stroke.*|fill.*|base.*|data.*|clip.*|overflow)' } },
        'removeElementsByAttr',
        'removeStyleElement',
        'removeScriptElement',
        'sortAttrs',
    ]
};
