const fs = require('fs');
const svgpath = require('svgpath');
const _ = require('lodash');


function svgFontTemplate(options) {
    const fontName = options.fontName;
    const glyphs = options.glyphs;

    return `<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg">
    <defs>
        <font id="${fontName}" horiz-adv-x="1024" horiz-adv-y="1024">
            <font-face font-family="${fontName}" units-per-em="1024" ascent="960" descent="-64" />
            <missing-glyph />
            <glyph unicode="&#x20;" d="" />
${glyphs.map(glyph => `
            <glyph unicode="&#x${glyph.unicode};" glyph-name="${glyph.name}" d="${glyph.d ? svgpath(glyph.d).translate(0, -22.5).scale(128 / 3, -128 / 3).toString() : ''}" />`).join('')}
        </font>
    </defs>
</svg>`;
}

function fontFileTemplate(fontFile) {
    const base64 = fs.readFileSync(fontFile).toString("base64");

    return `$ki-font-data-url: "data:font/ttf;base64,${base64}" !default;\n`;
}

function obsoleteAttribute( deprecated ) {
    if ( !deprecated ) {
        return '';
    }

    const reason = deprecated.replacement
        ? `Use ${_.upperFirst( _.camelCase( deprecated.replacement ) )} instead.`
        : 'This icon will be removed without a replacement.';
    const message = `since v4. Will be removed in v5. ${reason}`.replace(/"/g, '\\"');

    return `[System.Obsolete("${message}", false)]`;
}

function iconsCsTemplate( namespace, icons, deprecatedIcons = {} ) {
    return `// This file is auto-generated by the build process.
namespace ${namespace}
{
    public enum FontIcon
    {${icons.map(icon => {
        const deprecated = icon.name in deprecatedIcons
            ? { replacement: deprecatedIcons[icon.name] || null }
            : undefined;
        const obsolete = obsoleteAttribute( deprecated );
        return `
        ${obsolete ? `${obsolete}\n        ` : ''}${_.upperFirst( _.camelCase(icon.name) )} = ${icon.id}`;
    }).join(',')}
    }
}\n`;
}


module.exports.svgFontTemplate = svgFontTemplate;
module.exports.fontFileTemplate = fontFileTemplate;
module.exports.iconsCsTemplate = iconsCsTemplate;
