function svgTsTemplate( options ) {
    const { iconName, iconTsName, iconSvgContent, variants, deprecated } = options;

    const lines = [
        `    name: '${iconName}'`,
        `    content: '<path d="${iconSvgContent}" />'`,
        `    viewBox: '0 0 512 512'`
    ];

    if (variants && Object.keys(variants).length) {
        const variantEntries = Object.entries(variants).map(([ key, val ]) => {
            const escapedContent = val ? val.replace(/'/g, "\\'") : '';
            return `        '${key}': '${escapedContent}'`;
        }).join(',\n');
        lines.push(`    variants: {\n${variantEntries}\n    }`);
    }

    let jsdoc = '';
    if (deprecated) {
        const reason = deprecated.replacement
            ? `Use \`${deprecated.replacement}\` instead.`
            : 'This icon will be removed without a replacement.';
        jsdoc = `/**\n * @deprecated since v4. Will be removed in v5. ${reason}\n */\n`;
    }

    return `import { SVGIcon } from '../svg-icon.interface';

${jsdoc}export const ${iconTsName}: SVGIcon = {
${lines.join(',\n')}
}\n`;
}

function indexTsTemplate( options, aliasReExports ) {
    // Build a set of TS names that aliases will provide
    const aliasedTsNames = new Set(
        (aliasReExports || []).map(a => a.aliasTsName)
    );

    const iconExports = options.map(icon => {
        if (aliasedTsNames.has(icon.iconTsName)) {
            return `// export { ${icon.iconTsName} } from './icons/${icon.iconName}'; // superseded by alias`;
        }
        const exportLine = `export { ${icon.iconTsName} } from './icons/${icon.iconName}';`;
        if (icon.deprecated) {
            const reason = icon.deprecated.replacement
                ? `Use \`${icon.deprecated.replacement}\` instead.`
                : 'This icon will be removed without a replacement.';
            return `/** @deprecated since v4. Will be removed in v5. ${reason} */\n${exportLine}`;
        }
        return exportLine;
    }).join('\n');

    let aliasExports = '';
    if (aliasReExports && aliasReExports.length) {
        aliasExports = '\n\n// Alias re-exports: unsuffixed names pointing to -outline icons\n// TODO: remove alias with v5\n' +
            aliasReExports.map(a => `export { ${a.sourceTsName} as ${a.aliasTsName} } from './icons/${a.sourceIconName}';`).join('\n');
    }

    return `export { SVGIcon, SVGIconVariant } from './svg-icon.interface';

${iconExports}${aliasExports}\n`;
}

function svgCsTemplate( options ) {
    const { iconName, iconCsName, iconSvgContent, variants } = options;

    const lines = [
        `            Name = "${iconName}";`,
        `            Content = "<path d=\\"${iconSvgContent}\\" />";`,
        `            ViewBox = "0 0 512 512";`
    ];

    if (variants && Object.keys(variants).length) {
        const variantEntries = Object.entries(variants).map(([ key, val ]) => {
            const escapedContent = val ? val.replace(/"/g, '\\"') : '';
            return `                { "${key}", "${escapedContent}" }`;
        }).join(',\n');
        lines.push(`            Variants = new System.Collections.Generic.Dictionary<string, string>\n            {\n${variantEntries}\n            };`);
    }

    return `namespace Telerik.SvgIcons
{
    public class ${iconCsName} : SvgIconBase
    {
        public ${iconCsName}()
        {
${lines.join('\n')}
        }
    }
}\n`;
}

function indexCsTemplate( options, aliasReExports ) {
    const iconProps = options.map(icon => `
        public static ISvgIcon ${icon.iconCsName} => new ${icon.iconCsName}();`).join('');

    let aliasProps = '';
    if (aliasReExports && aliasReExports.length) {
        aliasProps = '\n\n        // Alias re-exports: unsuffixed names pointing to -outline icons' +
            aliasReExports.map(a => `\n        public static ISvgIcon ${a.aliasCsName} => ${a.sourceCsName};`).join('');
    }

    return `// This file is auto-generated by the build process.
namespace Telerik.SvgIcons
{
    public static class SvgIcon
    {${iconProps}${aliasProps}
    }
}\n`;
}


module.exports.svgTsTemplate = svgTsTemplate;
module.exports.indexTsTemplate = indexTsTemplate;
module.exports.svgCsTemplate = svgCsTemplate;
module.exports.indexCsTemplate = indexCsTemplate;
