function svgTsTemplate( options ) {
    const { iconName, iconTsName, iconSvgContent, tags, variants } = options;

    const lines = [
        `    name: '${iconName}'`,
        `    content: '<path d="${iconSvgContent}" />'`,
        `    viewBox: '0 0 512 512'`
    ];

    if (tags && tags.length) {
        lines.push(`    tags: ${JSON.stringify(tags)}`);
    }

    if (variants && Object.keys(variants).length) {
        const variantEntries = Object.entries(variants).map(([ key, val ]) => {
            const escapedContent = val ? val.replace(/'/g, "\\'") : '';
            return `        '${key}': '${escapedContent}'`;
        }).join(',\n');
        lines.push(`    variants: {\n${variantEntries}\n    }`);
    }

    return `import { SVGIcon } from '../svg-icon.interface';

export const ${iconTsName}: SVGIcon = {
${lines.join(',\n')}
}\n`;
}

function indexTsTemplate( options, aliasReExports ) {
    const iconExports = options.map(icon => `export { ${icon.iconTsName} } from './icons/${icon.iconName}';`).join('\n');

    let aliasExports = '';
    if (aliasReExports && aliasReExports.length) {
        aliasExports = '\n\n// Alias re-exports: unsuffixed names pointing to -outline icons\n' +
            aliasReExports.map(a => `export { ${a.sourceTsName} as ${a.aliasTsName} } from './icons/${a.sourceIconName}';`).join('\n');
    }

    return `export { SVGIcon, SVGIconVariant } from './svg-icon.interface';

${iconExports}${aliasExports}\n`;
}

function svgCsTemplate( options ) {
    const { iconName, iconCsName, iconSvgContent, tags, variants } = options;

    const lines = [
        `            Name = "${iconName}";`,
        `            Content = "<path d=\\"${iconSvgContent}\\" />";`,
        `            ViewBox = "0 0 512 512";`
    ];

    if (tags && tags.length) {
        lines.push(`            Tags = new string[] { ${tags.map(t => `"${t}"`).join(', ')} };`);
    }

    if (variants && Object.keys(variants).length) {
        const variantEntries = Object.entries(variants).map(([ key, val ]) => {
            const escapedContent = val ? val.replace(/"/g, '\\"') : '';
            return `                { "${key}", "${escapedContent}" }`;
        }).join(',\n');
        lines.push(`            Variants = new System.Collections.Generic.Dictionary<string, string>\n            {\n${variantEntries}\n            };`);
    }

    return `namespace Telerik.SvgIcons
{
    public class ${iconCsName} : SvgIconBase
    {
        public ${iconCsName}()
        {
${lines.join('\n')}
        }
    }
}\n`;
}

function indexCsTemplate( options, aliasReExports ) {
    const iconProps = options.map(icon => `
        public static ISvgIcon ${icon.iconCsName} => new ${icon.iconCsName}();`).join('');

    let aliasProps = '';
    if (aliasReExports && aliasReExports.length) {
        aliasProps = '\n\n        // Alias re-exports: unsuffixed names pointing to -outline icons' +
            aliasReExports.map(a => `\n        public static ISvgIcon ${a.aliasCsName} => ${a.sourceCsName};`).join('');
    }

    return `// This file is auto-generated by the build process.
namespace Telerik.SvgIcons
{
    public static class SvgIcon
    {${iconProps}${aliasProps}
    }
}\n`;
}


module.exports.svgTsTemplate = svgTsTemplate;
module.exports.indexTsTemplate = indexTsTemplate;
module.exports.svgCsTemplate = svgCsTemplate;
module.exports.indexCsTemplate = indexCsTemplate;
