#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run eslint
npm run update-icons

git diff --exit-code --quiet -- src/icons/ || (echo -e '\\033[0;31mERROR: icons.json is updated. Please add icon groups if new icons are added.' && exit 1)
