name: Merge develop to master

defaults:
  run:
    shell: bash

on: [workflow_dispatch]

jobs:

  merge:
    name: Merge
    runs-on: ubuntu-latest

    permissions:
        id-token: write # Required by Akeyless
        contents: read
        packages: read

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: '{ "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN" }'
          export-secrets-to-environment: false

      - name: Check out master
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0 # Fetch all branches
          token: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Merge develop to master
        run: |
          git fetch --quiet
          git reset --hard origin/master
          git merge --ff-only --quiet origin/develop
          git push origin master
