name: Move Tag

on: workflow_dispatch

jobs:
  move-tag:
    name: Move tag
    runs-on: ubuntu-latest
    environment: upload

    permissions:
        id-token: write # Required by Akeyless
        contents: read
        packages: read

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: |
            {
              "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN",
              "/WebComponents/prod/tokens/PROGRESS_NPM_REGISTRY_TOKEN": "NPM_TOKEN"
            }
          export-secrets-to-environment: false

      - name: Check out develop
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ steps.import-secrets.outputs.NPM_TOKEN }}

      - name: Move tag
        run: |
            npm dist-tag add @progress/kendo-font-icons@1.9.0 latest
            npm dist-tag add @progress/kendo-svg-icons@1.9.0 latest
