name: Publish to npm

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of release to publish'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stable
          - hotfix
      dry-run:
        description: 'Dry run (skip actual publish and push)'
        required: false
        default: false
        type: boolean

env:
  TARGET_BRANCH: ${{ github.event.inputs.release-type == 'dev' && 'develop' || github.event.inputs.release-type == 'hotfix' && 'release-v4.x' || 'master' }}
  DRY_RUN: ${{ github.event.inputs.dry-run == 'true' }}

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: upload

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read
      packages: read

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v5
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: |
            {
              "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN"
            }
          export-secrets-to-environment: false

      - name: Check out ${{ env.TARGET_BRANCH }}
        uses: actions/checkout@v6
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0 # Fetch all branches
          token: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Setup git
        run: |
          git config user.name "kendo-bot"
          git config user.email "kendouiteam@progress.com"

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm ci

      - name: Publish dev release
        if: ${{ github.event.inputs.release-type == 'dev' && env.DRY_RUN != 'true' }}
        run: |
          npx lerna publish \
            --conventional-commits --conventional-prerelease \
            --create-release github --preid dev --dist-tag dev \
            --allow-branch develop --force-publish --exact --yes
        env:
          GH_TOKEN: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Dry run dev release
        if: ${{ github.event.inputs.release-type == 'dev' && env.DRY_RUN == 'true' }}
        run: |
          npx lerna version \
            --conventional-commits --conventional-prerelease \
            --preid dev --allow-branch develop \
            --force-publish --exact --yes --no-push

      - name: Merge develop to master
        if: ${{ github.event.inputs.release-type == 'stable' && github.event.inputs.dry-run != 'true' }}
        run: |
          git fetch --quiet
          git reset --hard origin/master
          git merge --ff-only --quiet origin/develop

      - name: Publish stable release
        if: ${{ github.event.inputs.release-type == 'stable' && env.DRY_RUN != 'true' }}
        run: |
          npx lerna publish \
            --conventional-commits --conventional-graduate \
            --create-release github --force-publish --exact
        env:
          GH_TOKEN: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Dry run stable release
        if: ${{ github.event.inputs.release-type == 'stable' && env.DRY_RUN == 'true' }}
        run: |
          npx lerna version \
            --conventional-commits --conventional-graduate \
            --force-publish --exact --yes --no-push

      - name: Push to GitHub
        if: ${{ github.event.inputs.release-type == 'stable' && github.event.inputs.dry-run != 'true' }}
        run: |
          git push origin master --tags --quiet > /dev/null 2>&1
          git push origin master:develop --quiet > /dev/null 2>&1

      - name: Publish hotfix release
        if: ${{ github.event.inputs.release-type == 'hotfix' && env.DRY_RUN != 'true' }}
        run: |
          cd packages/font-icons
          npm publish --tag v4
        env:
          GH_TOKEN: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Dry run hotfix release
        if: ${{ github.event.inputs.release-type == 'hotfix' && env.DRY_RUN == 'true' }}
        run: |
          npx lerna version \
            --conventional-commits --conventional-graduate \
            --allow-branch release-v4.x \
            --force-publish --exact --yes --no-push

      - name: Push hotfix to GitHub
        if: ${{ github.event.inputs.release-type == 'hotfix' && github.event.inputs.dry-run != 'true' }}
        run: |
          git push origin release-v4.x --tags --quiet > /dev/null 2>&1
