name: Publish to nuget

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Publish to npm"
    types:
      - completed

jobs:

  nuget-publish:
    runs-on: ubuntu-latest

    env:
      FONT_ICONS: "packages/font-icons/src-cs/Telerik.FontIcons"
      SVG_ICONS: "packages/svg-icons/src-cs/Telerik.SvgIcons"

    steps:

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 14.x

      - name: Install
        run: |
          npm ci
          npm run bootstrap

      - name: Build assets
        run: |
          npm run build

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x

      - name: Build projects
        run: |
          dotnet build -c Release ${{ env.FONT_ICONS }}/Telerik.FontIcons.csproj
          dotnet build -c Release ${{ env.SVG_ICONS }}/Telerik.SvgIcons.csproj

      - name: Pack font icons nuget
        run: |
          VERSION=$(jq '.version' packages/font-icons/package.json)
          dotnet pack -c Release ${{ env.FONT_ICONS }}/Telerik.FontIcons.csproj -p:PackageVersion=$VERSION

      - name: Pack svg icons nuget
        run: |
          VERSION=$(jq '.version' packages/svg-icons/package.json)
          dotnet pack -c Release ${{ env.SVG_ICONS }}/Telerik.SvgIcons.csproj -p:PackageVersion=$VERSION

      - name: Push nuget packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
        run: |
          dotnet nuget push ${{ env.FONT_ICONS }}/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s ${{ env.NUGET_SOURCE }} --skip-duplicate
          dotnet nuget push ${{ env.SVG_ICONS }}/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s ${{ env.NUGET_SOURCE }} --skip-duplicate
